- name: Create jellyfin
  include_role:
    name: proxmox_create_lxc
  vars:
    unprivileged: true
    pve_node: ubuntuserver
    pve_hostname: jellyfin
    pve_lxc_vmid: 202
    pve_lxc_net_interfaces:
      - id: net0
        name: eth0
        hwaddr: 0E:4A:3A:04:C0:65
        ip4: 10.0.1.8
        netmask4: 23
        gw4: 10.0.0.1
        bridge: vmbr0
    pve_lxc_additional_configurations:
      - regexp: "^mp0"
        line: "mp0: /bulk/data,mp=/data"
        state: present
      - regexp: "c 195:\\* rwm"
        line: "lxc.cgroup2.devices.allow: c 195:* rwm"
        state: present
      - regexp: "c 235:\\* rwm"
        line: "lxc.cgroup2.devices.allow: c 235:* rwm"
        state: present
      - regexp: "c 236:\\* rwm"
        line: "lxc.cgroup2.devices.allow: c 238:* rwm"
        state: present
      - regexp: /dev/nvidia0
        line: "lxc.mount.entry: /dev/nvidia0 dev/nvidia0 none bind,optional,create=file"
        state: present
      - regexp: /dev/nvidiactl
        line: "lxc.mount.entry: /dev/nvidiactl dev/nvidiactl none bind,optional,create=file"
        state: present
      - regexp: dev/nvidia-uvm none
        line: "lxc.mount.entry: /dev/nvidia-uvm dev/nvidia-uvm none bind,optional,create=file"
        state: present
      - regexp: /dev/nvidia-modeset
        line: "lxc.mount.entry: /dev/nvidia-modeset dev/nvidia-modeset none bind,optional,create=file"
        state: present
      - regexp: "dev/nvidia-uvm-tools none"
        line: "lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-uvm-tools none bind,optional,create=file"
        state: present
      - regexp: nvidia-cap1
        line: "lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-caps/nvidia-cap1 none bind,optional,create=file"
        state: present
      - regexp: nvidia-cap2
        line: "lxc.mount.entry: /dev/nvidia-uvm-tools dev/nvidia-caps/nvidia-cap2 none bind,optional,create=file"
        state: present
- name: Create transmission
  include_role:
    name: proxmox_create_lxc
  vars:
    unprivileged: true
    pve_node: ubuntuserver
    pve_hostname: transmission
    pve_lxc_vmid: 201
    pve_lxc_net_interfaces:
      - id: net0
        name: eth0
        hwaddr: ce:e1:58:89:de:d2
        ip4: dhcp
        ip6: dhcp
        bridge: vmbr0
    pve_lxc_additional_configurations:
      - regexp: "^mp0"
        line: "mp0: /bulk/data,mp=/data"
        state: present
      - regexp: "/dev/net"
        line: "lxc.mount.entry: /dev/net dev/net none bind,create=dir"
        state: present
      - regexp: "^lxc.cgroup2"
        line: "lxc.cgroup2.devices.allow: c 10:200 rwm"
        state: present
- name: Create immich
  include_role:
    name: proxmox_create_lxc
  vars:
    pve_lxc_disk: 32
    unprivileged: true
    pve_node: alexa-desktop
    pve_hostname: immich
    pve_lxc_vmid: 104
    pve_lxc_memory: 4096
    pve_lxc_swap: 4096
    pve_lxc_net_interfaces:
      - id: net0
        name: eth0
        hwaddr: 86:ab:4f:a2:33:78
        ip4: dhcp
        ip6: dhcp
        bridge: vmbr0
    pve_lxc_additional_configurations:
      - regexp: "^mp0"
        line: "mp0: /storage-pool/data/immich,mp=/data"
        state: present
- name: Create unifi
  include_role:
    name: proxmox_create_lxc
  vars:
    unprivileged: true
    pve_node: alexa-desktop
    pve_hostname: unifi
    pve_lxc_vmid: 100
    pve_lxc_memory: 1024
    pve_lxc_swap: 1024
    pve_lxc_net_interfaces:
      - id: net0
        name: eth0
        hwaddr: 56:01:ab:fb:71:db
        ip4: dhcp
        ip6: dhcp
        bridge: vmbr0
- name: Create caddy
  include_role:
    name: proxmox_create_lxc
  vars:
    unprivileged: true
    pve_node: alexa-desktop
    pve_hostname: caddy
    pve_lxc_vmid: 103
    pve_lxc_memory: 256
    pve_lxc_swap: 256
    pve_lxc_net_interfaces:
      - id: net0
        name: eth0
        hwaddr: ae:b3:d5:3f:40:15
        ip4: dhcp
        ip6: dhcp
        bridge: vmbr0
- name: Create heimdall
  include_role:
    name: proxmox_create_lxc
  vars:
    unprivileged: true
    pve_node: alexa-desktop
    pve_hostname: heimdall
    pve_lxc_vmid: 102
    pve_lxc_memory: 128
    pve_lxc_swap: 128
    pve_lxc_net_interfaces:
      - id: net0
        name: eth0
        hwaddr: 6c:ca:64:b2:e1:7b
        ip4: dhcp
        ip6: dhcp
        bridge: vmbr0
