version: 0.1
log:
  fields:
    service: registry
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
  delete:
    enabled: true
  maintenance:
    uploadpurging:
      enabled: true
      age: 168h
      interval: 24h
      dryrun: false
http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
  tls:
    letsencrypt:
      cachefile: /cache
      email: registry@lavallee.one
      hosts: ["registry.ci"]
      directoryurl: "https://step.lan/acme/ACME/directory"
auth:
  token:
    realm: https://auth.ci/auth
    service: Authentication
    issuer: ci-issuer
    rootcertbundle: /usr/local/share/ca-certificates/registry.crt
validation:
  enabled: true
  disabled: false
  manifests:
    urls:
      allow: [".*"]
      deny: []
health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
