- name: Update caddy config
  include_role:
    name: caddy_ansible.caddy_ansible
  vars:
    caddy_environment_variables:
      CF_KEY: "{{CF_KEY}}"
    caddy_systemd_capabilities_enabled: true
    caddy_config: "{{ lookup('file', 'config/Caddyfile') }}"
    caddy_packages: [github.com/caddy-dns/cloudflare]
