- name: Enable contrib and non-free repository
  when: ansible_distribution == 'Debian'
  apt_repository:
    repo: "{{ item }}"
  loop:
    - "deb http://http.us.debian.org/debian bullseye contrib"
    - "deb http://http.us.debian.org/debian bullseye non-free"
- name: Install python3-apt and sudo
  ansible.builtin.apt:
    pkg:
      - python3-apt
      - sudo
      - curl
    update_cache: true
- name: Apt upgrade
  ansible.builtin.apt:
    upgrade: full
    update_cache: true
