- name: Enable backports
  apt_repository:
    repo: "deb http://deb.debian.org/debian bullseye-backports main contrib non-free"
- name: Install dependencies
  ansible.builtin.apt:
    pkg:
      - git
      - apache2
      - php
      - libapache2-mod-php
      - sqlite3
      - php-mbstring
      - php-xml
      - php-common
      - php-sqlite3
      - php-zip
      - composer
    update_cache: true
    default_release: bullseye-backports
- name: Enable the Apache2 module rewrite
  community.general.apache2_module:
    state: present
    name: rewrite
  notify: restart apache2
- name: Copy 000-default.conf
  copy:
    src: config/000-default.conf
    dest: /etc/apache2/sites-enabled/000-default.conf
  notify: restart apache2
- name: Download heimdall
  ansible.builtin.git:
    repo: https://github.com/linuxserver/Heimdall.git
    separate_git_dir: /opt/heimdall-git
    dest: /opt/heimdall
    version: 2.x
  environment:
    GIT_CONFIG_COUNT: "2"
    GIT_CONFIG_KEY_0: "safe.directory"
    GIT_CONFIG_VALUE_0: "/opt/heimdall"
    GIT_CONFIG_KEY_1: "core.filemode"
    GIT_CONFIG_VALUE_1: "false"
- name: Install laravel/installer
  community.general.composer:
    command: require
    global_command: true
    arguments: laravel/installer
    working_dir: /opt/heimdall
- name: Give www-data ownership of folder
  ansible.builtin.file:
    path: /opt/heimdall/
    owner: www-data
    group: www-data
    # mode: "0755"
    recurse: true
