- name: Copy docker.gpg
  copy:
    src: gpg/docker.gpg
    dest: /etc/apt/trusted.gpg.d/
- name: Enable docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/debian bullseye stable"
- name: Install docker
  ansible.builtin.apt:
    pkg:
      - docker-ce
      - python3-pip
      - containerd.io
- name: Install docker python package
  ansible.builtin.pip:
    name: "{{item}}"
  with_items:
    - docker
    - docker-compose
- community.docker.docker_compose_v2:
    project_name: immich
    pull: always
    definition:
      version: "3.8"

      services:
        immich-server:
          container_name: immich_server
          image: ghcr.io/immich-app/immich-server:release
          volumes:
            - /data:/usr/src/app/upload
          environment:
            TZ: "America/Los_Angeles"
            DB_HOSTNAME: database
            DB_USERNAME: postgres
            DB_PASSWORD: postgres
            DB_DATABASE_NAME: immich
            REDIS_HOSTNAME: immich_redis
          depends_on:
            - redis
            - database
          ports:
            - "80:2283"
          restart: always

        immich-machine-learning:
          container_name: immich_machine_learning
          image: ghcr.io/immich-app/immich-machine-learning:release
          volumes:
            - /data:/usr/src/app/upload
            - model-cache:/cache
          environment:
            TZ: "America/Los_Angeles"
          restart: always

        redis:
          container_name: immich_redis
          image: redis:6.2-alpine@sha256:70a7a5b641117670beae0d80658430853896b5ef269ccf00d1827427e3263fa3
          restart: always
          environment:
            TZ: "America/Los_Angeles"

        database:
          container_name: immich_postgres
          image: tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
          environment:
            TZ: "America/Los_Angeles"
            POSTGRES_PASSWORD: postgres
            POSTGRES_USER: postgres
            POSTGRES_DB: immich
            PG_DATA: /var/lib/postgresql/data
          volumes:
            - /data/db:/var/lib/postgresql/data
          restart: always

      volumes:
        model-cache:
