- name: Copy unifi-repo.gpg
  copy:
    src: "{{item}}"
    dest: /etc/apt/trusted.gpg.d/
  with_items:
    - "gpg/unifi-repo.gpg"
    - "gpg/mongodb-server-6.0.gpg"
- name: Enable unifi and mongodb repo
  apt_repository:
    repo: "{{item}}"
  with_items:
    - "deb [ signed-by=/etc/apt/trusted.gpg.d/mongodb-server-6.0.gpg] https://repo.mongodb.org/apt/debian bullseye/mongodb-org/6.0 main"
    - "deb https://www.ui.com/downloads/unifi/debian stable ubiquiti"
- name: Install Unifi
  ansible.builtin.apt:
    pkg:
      - unifi
    update_cache: true
