---
- hosts: vps

  tags:
    - essential

  tasks:
    - import_tasks: tasks/essential.yml
- hosts: pve01

  tags:
    - essential
  tasks:
    - import_tasks: tasks/essential.yml
- hosts: pve01
  tags:
    - pve

  tasks:
    - import_tasks: tasks/pve/main.yml
- hosts: alexa-desktop.lan
  tags:
    - lxc

  tasks:
    - import_tasks: tasks/pve/lxc.yml
- hosts: sshca.lan

  tasks:
    - import_tasks: tasks/sshca.yml
  tags:
    - sshca-host
- hosts: all
  vars:
    ansible_ssh_host_key_checking: False
    ansible_ssh_common_args: '-o "UserKnownHostsFile /dev/null"'

  handlers:
    - import_tasks: handlers/sshca.yml

  tasks:
    - import_tasks: tasks/sshca-host.yml
  tags:
    - sshca
- hosts: step.lan

  tags:
    - step

  tasks:
    - import_tasks: tasks/step.yml
  handlers:
    - import_tasks: handlers/step.yml
- hosts: pve01,ct

  tasks:
    - import_tasks: tasks/step-host.yml
  tags:
    - step
- hosts: ct

  tags:
    - essential

  tasks:
    - import_tasks: tasks/essential.yml
- hosts: ubuntuserver.lan
  tasks:
    - import_tasks: tasks/nvidia-drivers.yml
- hosts: alexa-desktop.lan
  tags:
    - smb
  tasks:
    - import_tasks: tasks/samba.yml
  handlers:
    - import_tasks: handlers/smb.yml
- hosts: transmission.lan

  tags:
    - transmission

  handlers:
    - import_tasks: handlers/transmission.yml

  tasks:
    - import_tasks: tasks/transmission.yml
- hosts: jellyfin.lan
  tasks:
    - import_tasks: tasks/jellyfin.yml
- hosts: unifi.lan

  tags:
    - unifi

  tasks:
    - import_tasks: tasks/unifi.yml
- hosts: caddy.lan

  tags:
    - caddy
  tasks:
    - import_tasks: tasks/caddy.yml
- hosts: immich.lan

  tags:
    - immich

  tasks:
    - import_tasks: tasks/immich.yml
- hosts: meepzee.lan

  tags:
    - ci

  tasks:
    - import_tasks: tasks/ContinuousIntegration.yml
- hosts: racknerd

  tags:
    - lemmios

  tasks:
    - import_tasks: tasks/lemmios.yml
- hosts: bitwarden.lan
  tags:
    - bitwarden
  tasks:
    - import_tasks: tasks/bitwarden.yml
